server_name: Galaxy Australia
smtp_server: localhost
from_addr: someone@somewhere.org
pg_host: <dbserver address>
pg_port: <port>
pg_user: galaxy
pg_dbname: galaxy
pg_password: <password>
warn_weeks: 11
delete_weeks: 13
