---
# defaults for telegraf

telegraf_agent_version: "{{ telegraf_version }}"
telegraf_download_url: "{{ telegraf_url }}"
telegraf_agent_hostname: "{{ hostname_prefix }}.{{ ansible_fqdn }}"
telegraf_agent_interval: 10
telegraf_agent_debug: False
telegraf_agent_round_interval: True
telegraf_agent_flush_interval: 10
telegraf_agent_flush_jitter: 0
telegraf_agent_collection_jitter: 0
telegraf_agent_metric_batch_size: 1000
telegraf_agent_metric_buffer_limit: 10000
telegraf_agent_quiet: False
telegraf_agent_logfile: ""
telegraf_agent_omit_hostname: False

telegraf_global_tags: []

telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["{{ stats_server }}"]
      - database = "{{ stats_database }}"
      - precision = "s"

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: net
  - plugin: system
  - plugin: swap
  - plugin: netstat

telegraf_plugins_extra:
