---
# This set of tasks will install telegraf and set the config.

# Install telegraf from the telegraf github
- name: Install telegraf as .deb file from telegraf's github
  apt:
      deb: "{{ telegraf_url }}"
      state: present
  become: yes
  become_user: root

- name: change permissions on the telegraf.d folder
  file:
      path: /etc/telegraf/telegraf.d
      state: directory
      owner: telegraf
      group: telegraf
      mode: 0755
  become: yes
  becmome_user: root

# copy the configuration template and restart telgraf
- name: Copy the config template to the correct location.
  template:
      src: telegraf.conf.j2
      dest: /etc/telegraf/telegraf.conf
      owner: telegraf
      group: telegraf
      mode: 0640
  become: yes
  notify: "Restart Telegraf"
